# docker-compose.override.yml (dev)
version: "3.7"
services:

  # WordPress on backend (from base) in development mode
  web:
    networks:
      - backend
    environment:
      WP_ENV: development
    volumes:
      - type: bind
        source: ./site
        target: /srv/web/app/site

  # Webpack DevServer exposed
  dev:
    image: nonfiction/bedrock:dev
    working_dir: /srv/web/app/site
    command: webpack-dev-server --hide-modules --hot
    volumes:
      - type: bind
        source: ./site
        target: /srv/web/app/site
      - type: volume
        source: node_modules
        target: /srv/web/app/site/node_modules
    expose:
      - 443
    networks:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${APP_HOST}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=digitalocean"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=443"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.scheme=https"
