# docker-compose.yml (base)
version: "3.7"
services:
  
  # Bedrock WordPress on Apache
  web:
    build: .
    image: nonfiction/bedrock-site:latest
    env_file: .env
    volumes:

      # # Bind source code to custom plugin dir
      # - type: bind
      #   source: ./site
      #   target: /srv/web/app/site

      # Volumes for persisting vendor, node_modules, uploads
      - type: volume
        source: vendor
        target: /srv/vendor
      - type: volume
        source: node_modules
        target: /srv/web/app/site/node_modules
      - type: volume
        source: uploads
        target: /srv/web/app/uploads

    expose: 
      - 443

  # WP-CLI
  wp:
    image: nonfiction/bedrock-site:latest
    env_file: .env
    entrypoint: /usr/local/bin/wp
    working_dir: /srv 
    command: ''
    volumes:
      - type: volume
        source: vendor
        target: /srv/vendor

# traefik reverse-proxy defined by docker-host 
networks:
  traefik:
    name: traefik
    external: true
  backend:

# speed up build times by storing packages, persist uploads
volumes:
  vendor:
  node_modules:
  uploads:
