# docker-compose.yml (base)
version: "3.7"
services:
  
  # Bedrock WordPress on Apache
  web:
    build: .
    image: nonfiction/bedrock-site:latest
    env_file: .env
    volumes:
      - type: volume
        source: uploads
        target: /srv/web/app/uploads
    expose: 
      - 443

  # WP-CLI
  wp:
    image: nonfiction/bedrock-site:latest
    env_file: .env
    entrypoint: /usr/local/bin/wp
    working_dir: /srv 
    command: 'core version'
    volumes:
      - type: volume
        source: uploads
        target: /srv/web/app/uploads

# traefik reverse-proxy defined by docker-host 
networks:
  traefik:
    name: traefik
    external: true

# persist uploads
volumes:
  uploads:
