version: '3.7'

services:
  web:
    build: .
    image: nonfiction/bedrock-site:latest
    volumes:
      # - type: bind
      #   source: .
      #   target: /srv/web/app/site
      - type: bind
        source: .env
        target: /srv/.env
    expose:
      - 80
    networks:
      - frontend
    environment:
      - VIRTUAL_HOST=site.${DOMAIN}

networks:
  frontend:
    name: frontend
    driver: bridge
