# docker-compose.yml (base)
version: "3.7"

# WordPress
services:
  web:
    build: .
    image: nonfiction/bedrock-site:latest
    env_file: .env
    volumes:

      # Bind source code to custom plugin dir
      - type: bind
        source: .
        target: /srv/web/app/site

      # Volumes for persisting vendor, node_modules
      - type: volume
        source: vendor
        target: /srv/vendor
      - type: volume
        source: node_modules
        target: /srv/web/app/site/node_modules/

    expose: 
      - 443

# traefik reverse-proxy defined by docker-host 
networks:
  traefik:
    name: traefik
    external: true
  backend:

# speed up build times by storing these
volumes:
  vendor:
  node_modules:
